# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='person',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
